### ISSUE TITLE
Remove worthless datastores

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-core#27]
We have a lot of datastores, and some of them are currently worthless.
- TinyDB should be removed since the peewee storage is faster and is also saved to a single file
- Should we remove the SQLite datastore? Could it possibly be an improvement over peewee or should we just scrap it?

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah I think we can get rid of both of them. The SQLite datastore was merely a curiosity of mine since it would mean easier porting to another language by using the declarative SQL syntax directly, but that's no longer of interest to me.

**Comment by ErikBjare** [comment]
You removed tinydb in the recent dev/next PR I believe, I just removed the sqlite one in  200fdc8.

Closing.
