### ISSUE TITLE
Size-limit JSON files

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-core#4]
Prevent JSON files (in the file storage method) from growing larger than a certain size (which takes considerable resources deserializing, storing in memory, and then again serializing). The previous proposal about date-naming is unnecessarily complex (which timezone should the dates be in, etc.) and it's just easier to start a new file when the last one gets too big.

This would require additional logic in the `get()` method, where it would have to read all the files, append them together, and return the contained events.

**Comment by johan-bjareholt** [comment]
The FileStorage method is no more, closing
