### ISSUE TITLE
Migration from peewee to sqlite loses some window titles

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/aw-core#87]
Migrating my own buckets through starting aw-server with an existing peewee-database and letting it auto-migrate lost some of my window title data.

This will need to be solved before (if) we migrate users. Also need to test if rust migrations have the same issue.

Blocks PR: https://github.com/ActivityWatch/aw-core/pull/86
![Screenshot 2020-02-19 at 11 52 29](https://user-images.githubusercontent.com/13387304/74822952-97398c00-530e-11ea-9cf6-92f1dc8dbe71.png)
The window titles existed before the migration.

There's also some new ` 2020-02-19 11:56:58 [WARNING]: Gap was of negative duration but could be safely merged (-7830.091s). This message will only show once per batch.  (aw_transform.flood:46) ` warnings too.

**Comment by ErikBjare** [comment]
Well that's worrying. I have no idea how that could happen, doesn't the migration just copy over the entire data field of all the events? 

The warning is unrelated.

**Comment by xylix** [comment]
Yes the [migration](https://github.com/ActivityWatch/aw-core/blob/f43bbf47d2f192e1d104babff94e2aa8f9f5f226/aw_datastore/migration.py#L33) seems to just copy over all the data. I'll try reproducing on a clean install and see what happens.

**Comment by ErikBjare** [comment]
Are you sure this happened in the migration and isn't an artifact of you
not giving ActivityWatch the accessibility permission? Because that would
give the exact same result...

**Comment by xylix** [comment]
Yes that does actually make a lot of sense, now that I looked the titles are only missing for the days after I updated to Catalina. But the issue is not with activitywatch's permissions.
<img width="337" alt="Screenshot 2020-02-19 at 14 57 51" src="https://user-images.githubusercontent.com/13387304/74836509-34ed8500-5328-11ea-97be-1cc6c6d59981.png">

I think it's most likely related to aw-watcher-window not having any permissions, since the .app starts it as a subprocess.

**Comment by xylix** [comment]
Oh right since this wasn't related to anything except macOS permissions I'll close this for now and if we see issues like this in the future probably open an issue in the main AW repo.

**Comment by ErikBjare** [comment]
There still needs to be a better indication what went wrong however. It would be a kinda nice improvement to new macOS users.

**Comment by ErikBjare** [comment]
There still needs to be a better indication what went wrong however. It would be a kinda nice improvement to new macOS users.

**Comment by xylix** [comment]
Did that.
